spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/todo_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: hzero
    password: hzero
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true


